### PR TITLE
Add wireless ip to localip + eye candy

### PR DESCRIPTION
**Pull request by jorenvanhee**
screen shot 2015-01-13 at 21 57 12

Maybe you'll like this :)

### CODE REVIEW

**Comment by emoju** [comment]
HI PAUL! Could you take a look at this its' nice.

**Comment by paulirish** [comment]
This is cool however on my machine en0 is wireless. 

Also lets move this to .functions since it's taking up more room.

**Comment by jorenvanhee** [comment]
I could also use en0 and en1 instead of wired and wireless.
Then it will work for everybody.

**Comment by paulirish** [comment]
mac only but how about this?

image

**Comment by jorenvanhee** [comment]
Nice!

**Pull request closed without merging**
